#pragma once

constexpr int THROTTLE_DEADBAND = 0;
constexpr int THROTTLE_MINIMUM_OUTPUT = 0;
constexpr float THROTTLE_EXPO_GAIN = 1.019;

constexpr int STEER_DEADBAND = 0;
constexpr int STEER_MINIMUM_OUTPUT = 0;
constexpr float STEER_EXPO_GAIN = 1.019;

constexpr float DESATURATION_BIAS = 0.75;

constexpr int INTAKE_SPEED = 127;
constexpr int OUTTAKE_FAST_SPEED = 127;
constexpr int OUTTAKE_SLOW_SPEED = 50; // TODO: change this back to 50

constexpr int KICKER_SPEED = 95;

#define THROTTLE_AXIS pros::E_CONTROLLER_ANALOG_LEFT_Y
#define STEER_AXIS pros::E_CONTROLLER_ANALOG_RIGHT_X

#define HANG_TOGGLE_BUTTON pros::E_CONTROLLER_DIGITAL_R1

#define INTAKE_BUTTON pros::E_CONTROLLER_DIGITAL_L1
#define OUTTAKE_BUTTON pros::E_CONTROLLER_DIGITAL_L2

#define LEFT_WING_BUTTON pros::E_CONTROLLER_DIGITAL_RIGHT
#define RIGHT_WING_BUTTON pros::E_CONTROLLER_DIGITAL_Y
#define ALL_WING_BUTTON pros::E_CONTROLLER_DIGITAL_R2

#define KICKER_BUTTON pros::E_CONTROLLER_DIGITAL_LEFT
